<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="0" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-16T03:15:40Z" name="Default suite" finished-at="2022-05-16T03:15:41Z" duration-ms="162">
    <groups>
    </groups>
    <test started-at="2022-05-16T03:15:40Z" name="Default test" finished-at="2022-05-16T03:15:41Z" duration-ms="162">
      <class name="testNG.TestDependencies">
        <test-method signature="orange()[pri:1, instance:testNG.TestDependencies@2177849e]" started-at="2022-05-16T03:15:40Z" name="orange" finished-at="2022-05-16T03:15:40Z" duration-ms="44" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orange -->
        <test-method signature="white()[pri:2, instance:testNG.TestDependencies@2177849e]" started-at="2022-05-16T03:15:40Z" name="white" finished-at="2022-05-16T03:15:40Z" depends-on-methods="testNG.TestDependencies.orange" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- white -->
        <test-method signature="blue()[pri:3, instance:testNG.TestDependencies@2177849e]" started-at="2022-05-16T03:15:40Z" name="blue" finished-at="2022-05-16T03:15:41Z" depends-on-methods="testNG.TestDependencies.white" duration-ms="18" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Blue test is Skipped...]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Blue test is Skipped...
at testNG.TestDependencies.blue(TestDependencies.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blue -->
        <test-method signature="green()[pri:4, instance:testNG.TestDependencies@2177849e]" started-at="2022-05-16T03:15:41Z" name="green" finished-at="2022-05-16T03:15:41Z" depends-on-methods="testNG.TestDependencies.blue" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDependencies.green()[pri:4, instance:testNG.TestDependencies@2177849e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDependencies.green()[pri:4, instance:testNG.TestDependencies@2177849e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- green -->
      </class> <!-- testNG.TestDependencies -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
